# Generated by Django 5.2.12 on 2026-04-05 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_mensajechat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportemascota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='reportemascota',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportemascota',
            name='tipo_reporte',
            field=models.CharField(choices=[('encontrado', 'Perrito Encontrado'), ('perdido', 'Busco Perrito Perdido')], default='encontrado', max_length=20),
        ),
        migrations.AddField(
            model_name='reportemascota',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagenReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mascotas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reportes.reportemascota')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
