# Generated by Django 5.2.12 on 2026-04-05 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_reportemascota_imagen_reportemascota_tamaño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosibleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_similitud', models.FloatField(help_text='Porcentaje de similitud (0-100)')),
                ('razon_match', models.TextField(help_text='Explicación de por qué estos reportes coinciden')),
                ('confirmado', models.BooleanField(default=False, help_text='Usuario confirmó que es su mascota')),
                ('desmentido', models.BooleanField(default=False, help_text='Usuario rechazó el match')),
                ('notificado', models.BooleanField(default=False, help_text='Se envió notificación al usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reporte_encontrado', models.ForeignKey(limit_choices_to={'tipo_reporte': 'encontrado'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_encontrado', to='reportes.reportemascota')),
                ('reporte_perdido', models.ForeignKey(limit_choices_to={'tipo_reporte': 'perdido'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_perdido', to='reportes.reportemascota')),
            ],
            options={
                'verbose_name_plural': 'Posibles Matches',
                'ordering': ['-score_similitud', '-fecha_creacion'],
                'unique_together': {('reporte_perdido', 'reporte_encontrado')},
            },
        ),
    ]
